### ISSUE TITLE
Can't use require in Node, only import?

### ISSUE THREAD

**Issue by brucem1976** [node-pop3/node-pop3#11]
So the std way of including things in a Node app is to use require - is there any way to do that instead of having to use import?

**Comment by brettz9** [comment]
Node is moving toward using ES6 Modules, the JavaScript standard which the Node docs point out "are the official standard format to package JavaScript code for reuse": https://nodejs.org/api/esm.html

But indeed Node has, and no doubt will continue for some time, to support the `require` syntax.

You can use that form as of version 0.6.0 (just published!) by using:

```js
const Pop3Command = require('node-pop3');
```

For your future reference if finding other such packages, while Node continues to support `main` in `package.json` to indicate the entry file for `require` statements (with the CJS `exports` or `module.exports` format allowing you to know how to require it), if present, `exports` will override `main`. You can see at https://github.com/node-pop3/node-pop3/blob/master/package.json#L7-L10 in our package, for `require` statements, `./lib/Command.js` is the main entry file. Since it uses `module.exports` now, you can just require it as above.

Note that before the version I just published, 0.6.0, you had to use `require('node-pop3).default`. (See https://github.com/59naga/babel-plugin-add-module-exports if you want to know why.)

Closing, as that should resolve, but feel free to comment further as needed.

**Comment by brucem1976** [comment]
@brettz9 awesome - can you just push that new tagged version so I can give it a try?

**Comment by brettz9** [comment]
Already done.

**Comment by brettz9** [comment]
Oh, sorry, hadn't pushed upstream. Now pushed.
