### ISSUE TITLE
LIST returns 265 messages

### ISSUE THREAD

**Issue by jamesjessian** [node-pop3/node-pop3#2]
Hi,
This is more of a question than an issue, and I know it probably isn't anything to do with your library, but probably something to do with the POP3 protocol that I can't work out...
But when I fire off a LIST command to my GMail account it returns 265 messages every time, and they are from about 5 years ago.  Is there any way to get the most recent messages instead of old ones?  How come it is limited to 265?  Presumably some behaviour of the server?
Many thanks for any advice.

**Comment by lianxh** [comment]
@bishbashbosh123 According the [POP3 protocol](https://tools.ietf.org/html/rfc1939#page-6), server will implement the sequence of messages by itself.

Two suggestions:

1. Use `UIDL` instead of `LIST` in Gmail, it works for me.
2. Check is there any other arguments about LIST in Gmail which can order the list and use `commend('LIST', 'param1', 'param2', ...)`

**Comment by brettz9** [comment]
Closing as answer was provided.
